---
- hosts: tag_Name_ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  roles:
    - common
    - install-deps
    - install-app
    - init-conf
    - configure-nginx
    - db-backup
    - firewall
    - kernelci-storage
